Update CustomPayloadFixer.java
You have an error in your plugin, that's why Forge users can't connect. This should fix the problem with players using Forge. 

What happens is, you are importing Charsets from bukkit instead of bungeecord. When a Forge user tries to connect, it goes through the REGISTER channel, and since Charsets class is not defined in bungeecord, it launches a wrong exception catched as exploit:
java.lang.NoClassDefFoundError: org/apache/commons/io/Charsets

A normal user doesn't fall into this, because they never reach the line where Charsets is.